### PR TITLE
add maven wrapper

### PR DESCRIPTION
**Pull request by isopov**
This will not require to install maven to local machine and will ensure that all contributors/users use the same maven version.

### CODE REVIEW

**Comment by giltene** [comment]
Can you elaborate on the problem this would solve? It seems like a lot of complication and specific dependency added just to gain maven-version independence. especially in such a small project. Are you seeing portability issues (across maven versions) with this project, or is this just a preventative measure?

**Comment by isopov** [comment]
My main problem is maven installation. But `../mvnw` works too it is not that hard to deal with a project without maven wrapper.

>specific dependency added

Sorry, what dependency?

**Comment by giltene** [comment]
> 
> > specific dependency added
> 
> Sorry, what dependency?

A dependency on maven wrapper, which involves including a binary in the repo, and depending on a download location being stable.

**Comment by isopov** [comment]
Sorry for bothering you. I'm not capable of arguing about this. Some projects react to such PR with `Great! Didn't knew that such thing exist`. Some do not. If you do not like - don't use it. It is completely optional. (As gradle wrapper, by the way. But contrary to this it is part of the gradle itself, so is not external dependency)

**Pull request closed without merging**
